name: "job-application"

services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: db_local
    ports:
      - "8899:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: